-- ashen_order_loader.lua

-- Load command scripts
dofile("scripts/custom/ashen_order/commands/buy.lua")
dofile("scripts/custom/ashen_order/commands/gold.lua")
dofile("scripts/custom/ashen_order/commands/save.lua")
dofile("scripts/custom/ashen_order/commands/goto.lua")
dofile("scripts/custom/ashen_order/commands/deletelocation.lua")
dofile("scripts/custom/ashen_order/commands/level.lua")
dofile("scripts/custom/ashen_order/commands/help.lua")
dofile("scripts/custom/ashen_order/commands/summon.lua")
dofile("scripts/custom/ashen_order/commands/savepet.lua")
dofile("scripts/custom/ashen_order/commands/loadpet.lua")
dofile("scripts/custom/ashen_order/commands/deletepet.lua")
dofile("scripts/custom/ashen_order/commands/clearbags.lua")
dofile("scripts/custom/ashen_order/commands/clearbuyback.lua")
dofile("scripts/custom/ashen_order/commands/addevent.lua")
dofile("scripts/custom/ashen_order/commands/startevent.lua")
dofile("scripts/custom/ashen_order/commands/endevent.lua")
dofile("scripts/custom/ashen_order/commands/listevents.lua")
dofile("scripts/custom/ashen_order/commands/fly.lua")
dofile("scripts/custom/ashen_order/commands/speed.lua")
dofile("scripts/custom/ashen_order/commands/buff.lua")
dofile("scripts/custom/ashen_order/commands/scale.lua")
dofile("scripts/custom/ashen_order/commands/morph.lua")
dofile("scripts/custom/ashen_order/commands/invisible.lua")
dofile("scripts/custom/ashen_order/commands/resetcooldowns.lua")
dofile("scripts/custom/ashen_order/commands/clearaura.lua")
dofile("scripts/custom/ashen_order/commands/summonobject.lua")
dofile("scripts/custom/ashen_order/commands/sethome.lua")
dofile("scripts/custom/ashen_order/commands/weather.lua")
dofile("scripts/custom/ashen_order/commands/time.lua")
dofile("scripts/custom/ashen_order/commands/duelreset.lua")
dofile("scripts/custom/ashen_order/commands/completequest.lua")

-- Load gossip scripts
dofile("scripts/custom/ashen_order/gossip/buyback_vendor.lua")
dofile("scripts/custom/ashen_order/gossip/trainer_master.lua")
dofile("scripts/custom/ashen_order/gossip/ultimate_vendor.lua")
